---
title: "01 Intro to the tidyverse"
author: "Ahmad Nadeem Saigol"
date: "2022-04-22"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
# Analysis of Sales of Bikes using R:

## Loading Libraries
```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(writexl)
```

## Importing Data
```{r}
bikes_tbl <- read_excel("00_data/01_raw_data/01_bike_sales/01_raw_data/bikes.xlsx")
bikeshops_tbl <- read_excel("00_data/01_raw_data/01_bike_sales/01_raw_data/bikeshops.xlsx")
orderlines_tbl <- read_excel("00_data/01_raw_data/01_bike_sales/01_raw_data/orderlines.xlsx")
```

## Joining Data
```{r}
bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))
```

## Wrangling Data
```{r}
bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>% 
  separate(col = location, into = c("city", "state"), sep = ", ") %>% 
  mutate(total.price= price*quantity) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))
```

## Analysis by location (state)

### Preparing Data
```{r}
sales_by_location_tbl <- bike_orderlines_wrangled_tbl %>% 
  group_by(state)%>%
  summarise(sales=sum(total_price)) %>%
  mutate(sales_in_euro = scales::dollar(sales, big.mark = ".", 
                                   decimal.mark = ",", 
                                   prefix = "", 
                                   suffix = " €"))
sales_by_location_tbl %>% select(-(sales))
```
### Results
```{r fig.width=12, fig.height=10}
sales_by_location_tbl %>% ggplot(aes(x = state, y = sales)) +
  geom_col(fill = "#2DC6D6") +
  geom_label(aes(label = sales_in_euro)) +
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title    = "Revenue by State",
    subtitle = "North Rhine-Westphalia had the highest revenue.",
    x = "",
    y = "Revenue"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Analysis by location (state) and year

### Preparing Data
```{r}
sales_by_year_location_tbl <- bike_orderlines_wrangled_tbl %>% 
  transmute(year = year(order_date), total_price, state) %>%
  group_by(year, state) %>%
  summarise(sales=sum(total_price)) %>%
  ungroup() %>%
  mutate(sales_in_euro = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))
sales_by_year_location_tbl %>% select(-(sales))
```
### Results
```{r plot, fig.width=12, fig.height=10}
sales_by_year_location_tbl %>% ggplot(aes(x = year, y = sales, fill = state)) +
  geom_col() +
  facet_wrap(~ state) +
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by year and location",
    fill = "Locations"
  ) +
  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
